name = "MetNets"
uuid = "e57bcde5-101c-47b4-bac9-e79e238e37d4"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.1.6"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
